databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: maiblog
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false