# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: MaiBlog_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: MaiBlog_test
  
production:
  <<: *default
  database: MaiBlog_production
  username: MaiBlog
  password: <%= ENV["MAIBLOG_DATABASE_PASSWORD"] %>
